### ISSUE TITLE
Extend PropertyFilteringMessageBodyWriter

### ISSUE THREAD

**Issue by RaphC** [HubSpot/jackson-jaxrs-propertyfiltering#9]
Hi,

Your lib is very nice. I have a suggestion to make. It will be kind if the PropertyFilteringMessageBodyWriter is extendable.  I have a similar BodyWriter which filter property according to a securityContext. I'd like to merge the tow BodyWriter in a single one but I have nowhere to extend the PropertyFilteringMessageBodyWriter.

You could add an empty method addPropertiesToFilter invoked at the end of the getProperties method which could be overriden like that.

  private Collection<String> getProperties(String name) {
    List<String> values = uriInfo.getQueryParameters().get(name);

    List<String> properties = new ArrayList<String>();
    if (values != null) {
      for (String value : values) {
        String[] parts = value.split(",");
        for (String part : parts) {
          part = part.trim();
          if (!part.isEmpty()) {
            properties.add(part);
          }
        }
      }
    }
    addPropertiesToFilter(properties);
    return properties;
  }

  protected void addPropertiesToFilter(properties) {
 }

Regards,

**Comment by jhaber** [comment]
I just pushed a few commits which should help with your use-case. [This](https://github.com/HubSpot/jackson-jaxrs-propertyfiltering/blob/347840b35f25fd8a630f46f2885c1d49bd44cc82/src/main/java/com/hubspot/jackson/jaxrs/PropertyFilteringMessageBodyWriter.java#L131) method is now `protected` and takes more arguments so you can override it and enable filtering by whatever rules you want, even if the endpoint isn't annotated with `@PropertyFiltering`. I also added [this](https://github.com/HubSpot/jackson-jaxrs-propertyfiltering/blob/347840b35f25fd8a630f46f2885c1d49bd44cc82/src/main/java/com/hubspot/jackson/jaxrs/PropertyFilteringMessageBodyWriter.java#L111-L113) `protected` method which can be overridden to manipulate the properties however you want before returning the `PropertyFilter`.

Let me know if you think this will work for your use-case and I can cut a new release

**Comment by RaphC** [comment]
perfect. 

Thank you

**Comment by jhaber** [comment]
I just released this as part of version 0.8.1 which should show up in Maven central soon

**Comment by RaphC** [comment]
Thank you.
